oidc:
  issuer-uri: https://dev-722658.okta.com/oauth2/default
  client-id: 0oa25ngkukJs2EWLE357

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-722658.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oa25ngkukJs2EWLE357
      resourceserver:
        jwt:
          issuer-uri: https://dev-722658.okta.com/oauth2/default